include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(PIC32MK_analog_read_example_default_library_list )

# Handle files with suffix s, for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_assemble)
add_library(PIC32MK_analog_read_example_default_default_XC32_assemble OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_assemble})
    PIC32MK_analog_read_example_default_default_XC32_assemble_rule(PIC32MK_analog_read_example_default_default_XC32_assemble)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_assemble>")

endif()

# Handle files with suffix S, for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_assembleWithPreprocess)
add_library(PIC32MK_analog_read_example_default_default_XC32_assembleWithPreprocess OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_assembleWithPreprocess})
    PIC32MK_analog_read_example_default_default_XC32_assembleWithPreprocess_rule(PIC32MK_analog_read_example_default_default_XC32_assembleWithPreprocess)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_assembleWithPreprocess>")

endif()

# Handle files with suffix [cC], for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_compile)
add_library(PIC32MK_analog_read_example_default_default_XC32_compile OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_compile})
    PIC32MK_analog_read_example_default_default_XC32_compile_rule(PIC32MK_analog_read_example_default_default_XC32_compile)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_compile>")

endif()

# Handle files with suffix cpp, for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_compile_cpp)
add_library(PIC32MK_analog_read_example_default_default_XC32_compile_cpp OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_compile_cpp})
    PIC32MK_analog_read_example_default_default_XC32_compile_cpp_rule(PIC32MK_analog_read_example_default_default_XC32_compile_cpp)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_compile_cpp>")

endif()

# Handle files with suffix [cC], for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_dependentObject)
add_library(PIC32MK_analog_read_example_default_default_XC32_dependentObject OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_dependentObject})
    PIC32MK_analog_read_example_default_default_XC32_dependentObject_rule(PIC32MK_analog_read_example_default_default_XC32_dependentObject)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_dependentObject>")

endif()

# Handle files with suffix elf, for group default-XC32
if(PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_bin2hex)
add_library(PIC32MK_analog_read_example_default_default_XC32_bin2hex OBJECT ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_bin2hex})
    PIC32MK_analog_read_example_default_default_XC32_bin2hex_rule(PIC32MK_analog_read_example_default_default_XC32_bin2hex)
    list(APPEND PIC32MK_analog_read_example_default_library_list "$<TARGET_OBJECTS:PIC32MK_analog_read_example_default_default_XC32_bin2hex>")

endif()


# Main target for this project
add_executable(PIC32MK_analog_read_example_default_image_PYkDLCb3 ${PIC32MK_analog_read_example_default_library_list})

set_target_properties(PIC32MK_analog_read_example_default_image_PYkDLCb3 PROPERTIES
    OUTPUT_NAME "default"
    SUFFIX ".elf"
    RUNTIME_OUTPUT_DIRECTORY "${PIC32MK_analog_read_example_default_output_dir}")
target_link_libraries(PIC32MK_analog_read_example_default_image_PYkDLCb3 PRIVATE ${PIC32MK_analog_read_example_default_default_XC32_FILE_TYPE_link})

# Add the link options from the rule file.
PIC32MK_analog_read_example_default_link_rule( PIC32MK_analog_read_example_default_image_PYkDLCb3)

# Call bin2hex function from the rule file
PIC32MK_analog_read_example_default_bin2hex_rule(PIC32MK_analog_read_example_default_image_PYkDLCb3)

